const SOURCES=[['libya-248','data/libya-248.json'],['libya-500','data/libya-500.json'],['eu','data/eu.json'],['epa','data/epa.json']];
const DB={}; const $=s=>document.querySelector(s);
const norm=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/ـ/g,'').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[^\p{L}\p{N}\s./-]/gu,' ').replace(/\s+/g,' ').trim();
const compact=s=>norm(s).replace(/[\s./-]/g,''); const isCAS=s=>/^\d{2,7}-\d{2}-\d$/.test(String(s||'').trim());
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function levenshtein(a,b){a=compact(a);b=compact(b);let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let q=[i];for(let j=1;j<=b.length;j++)q[j]=Math.min(q[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));p=q}return p[b.length]}
function fields(r){return [['name',r.name],['cas',r.cas]]}
function score(q,r){let nq=norm(q),best={v:0,type:'',field:''};for(const [key,x] of fields(r)){if(!x)continue;let nx=norm(x);if(isCAS(q)&&isCAS(x))return compact(q)===compact(x)?{v:100,type:'CAS مطابق تمامًا',field:x}:{v:0,type:'',field:''};if(nq===nx)return{v:100,type:'اسم مطابق',field:x};if(nq.length>=4&&nx.length>=4&&(nx.includes(nq)||nq.includes(nx))){const ratio=Math.min(nq.length,nx.length)/Math.max(nq.length,nx.length);if(ratio>=.72&&ratio*96>best.v)best={v:Math.round(ratio*96),type:'تطابق جزئي',field:x}}const m=Math.max(compact(nq).length,compact(nx).length);if(m){const v=100-levenshtein(nq,nx)/m*100;if(v>best.v)best={v:Math.round(v),type:'تشابه حرفي',field:x}}}return best}
function sourceLabel(k){return {'libya-248':'ليبيا، قرار 248 لسنة 2024','libya-500':'ليبيا، قرار 500 لسنة 2026',eu:'الاتحاد الأوروبي',epa:'USA / EPA'}[k]||k}
function status(r,k){if(k==='libya-248')return ['محظور','bad'];if(k==='libya-500'){if(r.status==='Approved')return ['معتمد','good'];if(r.status==='RAR')return ['قيد تقييم المخاطر','review'];return ['قيد المراجعة','review']}const s=String(r.status||'غير محدد');return [s.includes('Approved')||s==='مسموح'?'مسموح':s,['good','review'][0]]}
function search(q,pro=false){const out=[];for(const [k] of SOURCES)for(const r of (DB[k]?.rows||[])){const s=score(q,r);if(s.v>=80)out.push({k,r,s})}const rank={'libya-248':0,'libya-500':1,eu:2,epa:3};out.sort((a,b)=>(rank[a.k]-rank[b.k])||b.s.v-a.s.v);return out.slice(0,pro?80:16)}
function render(results,q){const box=$('#results');$('#resultTitle').textContent=`نتائج الفحص${q?' لـ «'+q+'»':''}`;if(!results.length){box.innerHTML='<div class="notice warn"><b>لم يتم العثور على تطابق موثوق</b><br>عدم العثور على المادة لا يعني أنها مسموحة. جرّب الاسم الكامل أو رقم CAS.</div>';return}box.innerHTML=results.map(x=>{const [st,cl]=status(x.r,x.k);return `<article class="result ${x.s.v<90?'possible':''}"><div class="result-top"><div><span class="source">${sourceLabel(x.k)}</span><h3>${esc(x.r.name||'بدون اسم')}</h3></div><strong>${x.s.v}%</strong></div><p class="status ${cl}">${st}</p><p class="meta">CAS: ${esc(x.r.cas||'غير متوفر')} · التصنيف: ${esc(x.r.category||'غير مصنف')}</p><p class="match">${x.s.type}: ${esc(x.s.field)}</p>${x.s.v<90?'<p class="caution">تطابق محتمل، راجع الاسم والملصق قبل الاستخدام.</p>':''}</article>`}).join('')}
function updateState(){const n=SOURCES.reduce((a,[k])=>a+(DB[k]?.rows?.length||0),0);$('#dbState').textContent=n?'القواعد المحلية جاهزة':'القواعد غير متاحة';$('#dbCount').textContent=n.toLocaleString('en-US')+' سجل';$('#offlineState').textContent=navigator.onLine?'🟢 متصل':'🔴 بدون إنترنت'}
async function loadSource(k,url){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();DB[k]=data;await putLocal(k,data);return true}catch(e){const local=await getLocal(k);DB[k]=local||{rows:[]};return false}}
function openIDB(){return new Promise((res,rej)=>{const r=indexedDB.open('mustashar-local',1);r.onupgradeneeded=()=>r.result.createObjectStore('db');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putLocal(k,v){try{const db=await openIDB();const tx=db.transaction('db','readwrite');tx.objectStore('db').put(v,k)}catch(e){}}
async function getLocal(k){try{const db=await openIDB();return await new Promise((res,rej)=>{const r=db.transaction('db').objectStore('db').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}catch(e){return null}}
async function load(){for(const [k,u] of SOURCES)await loadSource(k,u);updateState();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#query').value.trim();if(q)render(search(q,$('#mode').value==='pro'),q)});
$('#mode').addEventListener('change',()=>{$('#modeLabel').textContent=$('#mode').value==='pro'?'المحترف':'المزارع'});window.addEventListener('online',updateState);window.addEventListener('offline',updateState);
const camera=$('#camera'),preview=$('#preview'),ocrMsg=$('#ocrMsg');$('#cameraBtn').addEventListener('click',()=>camera.click());camera.addEventListener('change',()=>{const f=camera.files?.[0];if(!f)return;preview.src=URL.createObjectURL(f);preview.hidden=false;ocrMsg.textContent='الصورة جاهزة. أضف محرك OCR المحلي داخل tess/ لتفعيل القراءة التلقائية.';$('#scanPanel').open=true});
$('#copyBtn').addEventListener('click',()=>navigator.clipboard?.writeText($('#results').innerText));
load();
