#!/usr/bin/env node
/*
 * tests/ios-phase1.test.mjs — المرحلة الأولى: توافق iPhone/iOS Safari
 * ------------------------------------------------------------------
 * حوارس ثابتة للبنود 1-4 من المرحلة الأولى. كل بند يُفحص على الملف
 * الحقيقي الذي يحمله (لا نسخة مبسّطة):
 *   1) أيقونة 180px موجودة فعلاً في <head> (وليست رابطاً ميتاً)
 *   2) viewport-fit=cover + env(safe-area-inset-*) على الرأس والتنقل
 *   3) فيديو الكاميرا: autoplay+playsinline+muted، وسُلّم قيود ideal ينزل
 *      لأسفل، وفشل getUserMedia يفتح مدخل الالتقاط تلقائياً بلا نص فني
 *   4) بطاقة تثبيت iOS بخطوتين مرسومتين + كشف display-mode/standalone
 * التشغيل: node tests/ios-phase1.test.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
process.chdir(root);

let pass = 0, fail = 0;
const check = (name, cond, extra) => {
  if (cond) { pass++; console.log('  PASS ' + name); }
  else { fail++; console.log('  FAIL ' + name + (extra ? ' — ' + extra : '')); }
};

const html = fs.readFileSync('index.html', 'utf8');
const app = fs.readFileSync('src/app.js', 'utf8');
const i18n = fs.readFileSync('src/i18n.js', 'utf8');
const sw = fs.readFileSync('sw.js', 'utf8');
const gen = fs.readFileSync('scripts/generate-icons.cjs', 'utf8');

console.log('=== 1) أيقونة 180px ===');
{
  const m = html.match(/<link rel="apple-touch-icon" sizes="180x180" href="([^"]+)"/);
  check('the 180px apple-touch-icon is linked in <head>', !!m, html.slice(0, 0));
  check('it points at a real file in the repo', !!m && fs.existsSync(m[1]), m ? m[1] : 'no link');
  check('the file is a PNG', !!m && fs.readFileSync(m[1]).slice(1, 4).toString() === 'PNG');
  check('the icon is generated by the committed generator (reproducible)',
    gen.includes("icon-180.png"));
  check('the 180 icon is precached by the service worker (an installed app needs it offline)',
    sw.includes('icons/icon-180.png'));
  check('iOS standalone metadata is declared',
    html.includes('apple-mobile-web-app-capable') && html.includes('apple-mobile-web-app-title'));
}

console.log('=== 2) المنطقة الآمنة ===');
{
  check('viewport-fit=cover is on the viewport meta',
    /name="viewport"[^>]*viewport-fit=cover/.test(html));
  check('the fixed header clears the top inset',
    /height: calc\(56px \+ env\(safe-area-inset-top, 0px\)\)/.test(html)
    && /padding-top: env\(safe-area-inset-top, 0px\)/.test(html));
  check('the page content starts below the (now taller) header',
    (html.match(/padding: calc\(68px \+ env\(safe-area-inset-top, 0px\)\)/g) || []).length === 1
    && /main \{ padding-top: calc\(72px \+ env\(safe-area-inset-top, 0px\)\); \}/.test(html));
  check('the bottom nav clears the home-indicator inset',
    /padding-bottom: env\(safe-area-inset-bottom, 0px\)/.test(html));
}

console.log('=== 3) الكاميرا ===');
{
  check('the video element is autoplay + playsinline + muted',
    /<video id="liveVideo" playsinline muted autoplay>/.test(html));
  check('the video is played through the element API, never window.open',
    app.includes('liveVideo.play()'));
  const ladder = app.match(/const CAMERA_LADDER = \[([\s\S]*?)\];/);
  check('the camera ladder exists', !!ladder);
  const body = ladder ? ladder[1] : '';
  check('no rung uses an exact constraint (Safari rejects exact)',
    !/exact/.test(body), body);
  const ideals = [...body.matchAll(/ideal: (\d+)/g)].map(m => +m[1]);
  check('every rung is an ideal width/height pair', ideals.length % 2 === 0 && ideals.length >= 4,
    JSON.stringify(ideals));
  check('the ladder steps DOWN (720p first, never 1080p)',
    ideals.length >= 4 && ideals[0] === 1280 && ideals[1] === 720 && !body.includes('1920'),
    JSON.stringify(ideals));
  check('the last rung is the unconstrained catch-all',
    /\n\s*\{\}\s*\n/.test(body));
  check('a getUserMedia failure opens the capture input automatically',
    /fallback: 'capture-input'/.test(app) && /camera\.click\(\)/.test(app));
  check('the farmer is never shown the raw camera error text',
    !/ocrMsg\.textContent = cameraErrorText\(camErr\)/.test(app));
  check('the camera error text helper is no longer called from the live path',
    (app.match(/cameraErrorText\(/g) || []).length <= 1);
}

console.log('=== 4) بطاقة تثبيت iOS ===');
{
  check('the card exists with two steps', /id="iosInstallCard"/.test(html)
    && (html.match(/class="ios-step-ic"/g) || []).length === 2);
  check('the two steps are drawn with icons, not letters',
    /ios-step-ic" data-icon="share"/.test(html) && /ios-step-ic" data-icon="home"/.test(html));
  check('both icons are known meanings in the icon table',
    require('fs').readFileSync('src/icons.js', 'utf8').includes("'share':") &&
    require('fs').readFileSync('src/icons.js', 'utf8').includes("'home':"));
  check('standalone is detected through BOTH signals',
    /navigator\.standalone/.test(app) && /display-mode: standalone/.test(app));
  check('iPadOS-as-Mac is detected too (no "iPad" in the UA any more)',
    /Macintosh/.test(app) && /maxTouchPoints/.test(app));
  check('the card hides itself when already installed',
    /iosCard\.hidden = !\(isIOS\(\) && !isStandalone\(\)/.test(app));
  check('all three strings exist in the four dictionaries',
    ['iosinstall.title', 'iosinstall.step1', 'iosinstall.step2']
      .every(k => (i18n.match(new RegExp("'" + k + "':", 'g')) || []).length === 4));
  check('no emoji anywhere in the card (icons only)',
    !/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(html.match(/id="iosInstallCard"[\s\S]*?<\/div>\s*<\/div>/)[0]));
}

console.log('=== 5) pageshow / quota / persist ===');
{
  check('a restored tab (pageshow.persisted) rebuilds the OCR engine',
    /addEventListener\('pageshow'/.test(app) && /ev\.persisted/.test(app)
    && app.includes('OcrModule.resetEngine'));
  check('the OCR module exports that reset',
    /resetEngine/.test(fs.readFileSync('src/ocr.js', 'utf8'))
    && /resetEngine/.test(fs.readFileSync('src/ocr.js', 'utf8').match(/global\.OcrModule = \{[\s\S]*?\};/)[0]));
  check('the barcode layer is NOT given a fake reset (it builds per call)',
    !/BarcodeModule\.reset/.test(app));
  check('a QuotaExceeded from cache.put is caught and reported',
    /isQuotaError/.test(fs.readFileSync('src/ocr.js', 'utf8'))
    && /setQuotaSink/.test(fs.readFileSync('src/ocr.js', 'utf8'))
    && /OcrModule\.setQuotaSink/.test(app));
  check('the quota sink shows the same free-up-space hint as the IndexedDB path',
    (app.match(/quota\.hint/g) || []).length === 2);
  check('persistent storage is requested after installation',
    /window\.addEventListener\('appinstalled'[\s\S]{0,400}requestPersistence\(\)/.test(app));
}

console.log('================================');
console.log('PASS: ' + pass + '   FAIL: ' + fail);
process.exit(fail ? 1 : 0);
