/*
 * app.js — المستشار الزراعي
 * Improvements over the previous version (search semantics untouched):
 *   - fail-soft, parallel database loading with per-database status
 *   - IndexedDB v2 with safe versioning; valid cached data is never
 *     replaced by empty/invalid data; new "history" store
 *   - persistent-storage request so the browser keeps the offline data
 *   - version/update detection via version.json (cache + network);
 *     the app never deletes user data automatically
 *   - original regulatory status values are displayed verbatim and
 *     status_raw is shown where available; no interpretation added
 */
(function () {
  'use strict';

  const SOURCES = [
    { key: 'libya-248', url: 'data/libya-248.json', labelKey: 'db.src.248', label: 'ليبيا 248' },
    { key: 'libya-500', url: 'data/libya-500.json', labelKey: 'db.src.500', label: 'ليبيا 500' },
    { key: 'eu',        url: 'data/eu.json',        labelKey: 'db.src.eu',  label: 'الاتحاد الأوروبي' },
    { key: 'epa',       url: 'data/epa.json',       labelKey: 'db.src.epa', label: 'USA / EPA' },
    /* FAO/WHO Codex — generated by scripts/update-intl-dbs.mjs (update
     * agent). Libya (248/500) is NEVER written by that agent and stays
     * the primary reference; FAO loads fail-soft when the file exists. */
    { key: 'fao',       url: 'data/fao.json',       labelKey: 'db.src.fao', label: 'FAO / Codex' }
  ];

  const DB_NAME = 'mustashar-local';
  const DB_VERSION = 2;           // v1 = "db" store; v2 adds "history"
  const STORE_DB = 'db';
  const STORE_HISTORY = 'history';

  const $ = s => document.querySelector(s);

  /* i18n helpers (src/i18n.js loads before this file). Arabic fallbacks
   * keep every string working even if the i18n module failed to load. */
  const t = (k, fb) => (window.I18N ? I18N.t(k, fb) : fb);
  const tf = (k, fb, vars) => (window.I18N ? I18N.tf(k, fb, vars) : fb);

  /* ============================================================
   * IndexedDB (v2) — safe open/upgrade, never destroys valid data
   * ============================================================ */
  let dbPromise = null;

  function openDB() {
    if (dbPromise) return dbPromise;
    dbPromise = new Promise((resolve, reject) => {
      let req;
      try { req = indexedDB.open(DB_NAME, DB_VERSION); }
      catch (e) { reject(e); return; }

      req.onupgradeneeded = () => {
        const db = req.result;
        // v1 store: never drop it — it may hold valid cached data
        if (!db.objectStoreNames.contains(STORE_DB)) {
          db.createObjectStore(STORE_DB);
        }
        // v2 store: search history
        if (!db.objectStoreNames.contains(STORE_HISTORY)) {
          db.createObjectStore(STORE_HISTORY);
        }
      };
      req.onsuccess = () => resolve(req.result);
      req.onerror = () => reject(req.error);
      req.onblocked = () => reject(new Error('indexeddb blocked'));
    }).catch(err => { dbPromise = null; throw err; });
    return dbPromise;
  }

  function idbPut(store, key, value) {
    return openDB().then(db => new Promise((resolve, reject) => {
      const tx = db.transaction(store, 'readwrite');
      tx.objectStore(store).put(value, key);
      tx.oncomplete = resolve;
      tx.onerror = () => reject(tx.error);
      tx.onabort = () => reject(tx.error);
    }));
  }

  function idbGet(store, key) {
    return openDB().then(db => new Promise((resolve, reject) => {
      const tx = db.transaction(store, 'readonly');
      const rq = tx.objectStore(store).get(key);
      rq.onsuccess = () => resolve(rq.result);
      rq.onerror = () => reject(rq.error);
    }));
  }

  function idbGetAll(store) {
    return openDB().then(db => new Promise((resolve, reject) => {
      const tx = db.transaction(store, 'readonly');
      const rq = tx.objectStore(store).getAll();
      rq.onsuccess = () => resolve(rq.result || []);
      rq.onerror = () => reject(rq.error);
    }));
  }

  function idbClear(store) {
    return openDB().then(db => new Promise((resolve, reject) => {
      const tx = db.transaction(store, 'readwrite');
      tx.objectStore(store).clear();
      tx.oncomplete = resolve;
      tx.onerror = () => reject(tx.error);
      tx.onabort = () => reject(tx.error);
    }));
  }

  function idbDelete(store, key) {
    return openDB().then(db => new Promise((resolve, reject) => {
      const tx = db.transaction(store, 'readwrite');
      tx.objectStore(store).delete(key);
      tx.oncomplete = resolve;
      tx.onerror = () => reject(tx.error);
      tx.onabort = () => reject(tx.error);
    }));
  }

  /* ============================================================
   * Data validation — never replace valid data with empty data
   * ============================================================ */
  function looksValid(data) {
    return !!(data && typeof data === 'object'
      && data.meta && typeof data.meta === 'object' && data.meta.key
      && Array.isArray(data.rows));
  }

  /* ============================================================
   * Status of each database
   *   loading | ok     | cached  | unavailable
   * (ok = fresh from network; cached = loaded from IndexedDB)
   * ============================================================ */
  const state = {};
  SOURCES.forEach(s => { state[s.key] = { phase: 'loading', count: 0, fromCache: false }; });

  function statusText() {
    return {
      loading:      t('db.loading', 'جارٍ التحميل…'),
      ok:           t('db.ok', 'جاهز'),
      cached:       t('db.cached', 'جاهز (نسخة محلية)'),
      unavailable:  t('db.unavailable', 'غير متاح')
    };
  }
  const STATUS_CLASS = {
    loading: 'db-loading', ok: 'db-ok', cached: 'db-cached', unavailable: 'db-bad'
  };

  function renderDbStatus() {
    const ST = statusText();
    SOURCES.forEach(s => {
      const chip = $('#db-' + s.key);
      const st = state[s.key];
      if (!chip) return;
      chip.textContent = t(s.labelKey, s.label) + ': ' + ST[st.phase]
        + (st.count ? ' (' + st.count.toLocaleString('en-US') + ')' : '');
      chip.className = 'chip ' + STATUS_CLASS[st.phase];
    });
    const ready = SOURCES.filter(s => state[s.key].phase === 'ok' || state[s.key].phase === 'cached');
    const total = ready.reduce((a, s) => a + state[s.key].count, 0);
    const badge = $('#dbCount');
    if (badge) badge.textContent = total
      ? tf('db.count', '{n} سجل', { n: total.toLocaleString('en-US') })
      : t('db.count.none', 'لا توجد قواعد محمّلة');
    const overall = $('#dbState');
    if (overall) {
      if (!ready.length) overall.textContent = t('db.none', 'القواعد غير متاحة');
      else if (ready.length === SOURCES.length) overall.textContent = t('db.ready', 'القواعد المحلية جاهزة');
      else overall.textContent = tf('db.partial', 'جاهز جزئيًا ({n})', { n: ready.length + '/' + SOURCES.length });
    }
    const banner = $('#dbBanner');
    if (banner) {
      const bad = SOURCES.filter(s => state[s.key].phase === 'unavailable');
      if (!ready.length) {
        banner.hidden = false;
        banner.textContent = t('db.banner.error', 'تعذّر تحميل أي قاعدة بيانات.');
        banner.className = 'banner banner-error';
      } else if (bad.length) {
        banner.hidden = false;
        banner.className = 'banner banner-warn';
        banner.textContent = tf('db.banner.warn', 'تعذّر تحميل: {names}.',
          { names: bad.map(s => t(s.labelKey, s.label)).join(t('list.sep', '، ')) });
      } else {
        banner.hidden = true;
      }
    }
  }

  function setPhase(key, phase, count) {
    state[key].phase = phase;
    if (typeof count === 'number') state[key].count = count;
    renderDbStatus();
  }

  /* ============================================================
   * Loading — parallel + fail-soft.
   * Each source is independent: one failure never blocks others.
   * ============================================================ */
  function loadSource(src) {
    setPhase(src.key, 'loading');
    const attemptFetch = () => fetch(src.url, { cache: 'no-store' }).then(async res => {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      const data = await res.json();
      if (!looksValid(data)) throw new Error('invalid payload');
      return data;
    });

    return attemptFetch()
      .then(data => {
        DB[src.key] = data;
        setPhase(src.key, 'ok', data.rows.length);
        // cache after success; never overwrite a valid cache with bad data
        return idbPut(STORE_DB, src.key, data).catch(() => {});
      })
      .catch(() => attemptFetch()                 // one silent retry
        .then(data => {
          DB[src.key] = data;
          setPhase(src.key, 'ok', data.rows.length);
          return idbPut(STORE_DB, src.key, data).catch(() => {});
        })
        .catch(() =>
          // fall back to the cached copy (any version) if present
          idbGet(STORE_DB, src.key).then(cached => {
            if (looksValid(cached)) {
              DB[src.key] = cached;
              setPhase(src.key, 'cached', cached.rows.length);
            } else {
              // mark unavailable — search simply skips this source
              setPhase(src.key, 'unavailable');
            }
          }).catch(() => setPhase(src.key, 'unavailable'))
        ));
  }

  function loadAll() {
    SOURCES.forEach(loadSource);   // parallel; failures are independent
  }

  /* ============================================================
   * Persistent storage — keep offline data as long as possible
   * ============================================================ */
  function requestPersistence() {
    if (navigator.storage && navigator.storage.persist) {
      navigator.storage.persist().catch(() => {});
    }
  }

  /* ============================================================
   * Version / update detection (informational only; never deletes)
   * ============================================================ */
  function checkVersion() {
    if (!navigator.onLine) return;
    fetch('version.json', { cache: 'no-store' })
      .then(r => (r.ok ? r.json() : null))
      .then(info => {
        if (!info || !info.version) return;
        $('#dbState') && ($('#dbState').title = t('ver.title', 'الإصدار: {v} — بيانات: {d}')
          .replace('{v}', info.version)
          .replace('{d}', info.data_updated || t('ver.data.unknown', 'غير محدد')));
        idbGet(STORE_DB, 'app-version').then(prev => {
          if (prev && prev !== info.version) {
            const banner = $('#dbBanner');
            if (banner) {
              banner.hidden = false;
              banner.className = 'banner banner-info';
              banner.textContent = tf('update.banner', 'يتوفر إصدار جديد من التطبيق ({a} → {b}).',
                { a: prev, b: info.version });
            }
          }
          idbPut(STORE_DB, 'app-version', info.version).catch(() => {});
        }).catch(() => {});
      })
      .catch(() => {});
  }

  /* ============================================================
   * Rendering helpers
   * ============================================================ */
  function esc(s) {
    return String(s ?? '').replace(/[&<>'"]/g, m => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;'
    }[m]));
  }

  /* Source labels and status display — verbatim values, no reinterpretation */
  function sourceLabel(k) {
    return {
      'libya-248': t('src.248', 'ليبيا، قرار 248 لسنة 2024'),
      'libya-500': t('src.500', 'ليبيا، قرار 500 لسنة 2026'),
      'eu': t('src.eu', 'الاتحاد الأوروبي'),
      'epa': t('src.epa', 'USA / EPA'),
      'fao': t('src.fao', 'FAO/WHO كودكس')
    }[k] || k;
  }

  /* Per-source status display via the decision layer (src/cas.js):
   * each source is shown with its OWN vocabulary — never merged into one
   * verdict. Red (banned tone) is reserved for Libya decree 248 alone;
   * reference-source alerts are amber; everything else is neutral.
   * The raw source term stays beside the translation (never hidden). */
  function statusDisplay(r, k, showDetails) {
    const d = CasDissect.dissectStatus(r, k);
    const phrase = t(d.key, d.raw || '?');
    let extra = '';
    if (/^st\.500\./.test(d.key) && d.raw) extra = ' (' + d.raw + ')';   // code stays visible
    else if (showDetails && d.raw && d.raw !== phrase) extra = ' · ' + d.raw;
    if (d.rup) extra += ' · ' + t('st.epa.rup.note', 'استخدام مقيد (للمرخّصين فقط)');
    return { text: phrase + extra, tone: d.tone, raw: d.raw };
  }

  function render(results, q) {
    const box = $('#results');
    lastResults = results || [];
    $('#resultTitle').textContent = t('results.title2', 'نتائج الفحص') + (q ? t('results.for', ' لـ «{q}»').replace('{q}', q) : '');
    if (!results.length) {
      box.innerHTML = '<div class="notice warn"><b>' + t('results.none.t', 'لم يتم العثور على تطابق موثوق') + '</b><br>'
        + t('results.none.b', 'عدم العثور على المادة لا يعني أنها مسموحة.') + '</div>';
      return;
    }
    /* Prohibited-list warning (Libya decree 248): rendered only when a row
     * from that database actually matched (≥80%, enforced by SearchCore) —
     * it is never assumed or invented. Merged from the Base44 exploration. */
    const prohibited = results.filter(x => x.k === 'libya-248');
    const showDetails = $('#mode').value === 'pro';
    /* Ambiguity banner (decision layer): two different substances (different
     * CAS) in a near tie with no confirmed winner → both are shown and the
     * user is told to check the full name. Never auto-picked. */
    const amb = window.CasDissect ? CasDissect.ambiguity(results) : null;
    const ambHtml = amb
      ? '<div class="ambgroup">' + tf('results.ambiguous',
          '⚠️ نتيجة ملتبسة: توجد مادة أخرى مشابهة برقم كيميائي مختلف ({a} {va}% ↔ {b} {vb}%). تحقق من الاسم الكامل قبل أي قرار.',
          { a: esc(String(amb.a.r.name || '').split('\n')[0]), va: amb.a.s.v,
            b: esc(String(amb.b.r.name || '').split('\n')[0]), vb: amb.b.s.v })
        + '</div>'
      : '';
    box.innerHTML = ambHtml + (prohibited.length
      ? '<div class="prohibited">' + tf('results.prohibited',
          '⚠️ تحذير: هذه المادة مدرجة ضمن قائمة المبيدات المحظورة في ليبيا (قرار 248) — {name}',
          { name: esc(String(prohibited[0].r.name || '')).replace(/\n/g, ' · ') })
        + '</div>'
      : '')
      + results.map(x => {
      /* --- decision layer: per-source status, verdict class, CAS checks --- */
      const sd = statusDisplay(x.r, x.k, showDetails);
      const stClass = sd.tone === 'banned' ? 'bad' : (sd.tone === 'amber' ? 'review' : 'neutral');
      const isExact = window.CasDissect && CasDissect.classify(x.s.v) === 'exact';
      const verdict = isExact
        ? '<span class="verdict exact">' + t('verdict.exact', 'تطابق تام') + '</span>'
        : '<span class="verdict probable">' + t('verdict.probable', 'احتمالي — تحقق من الاسم الكامل') + '</span>';
      /* CAS display: every listed CAS is checksum-validated for display
       * (failed ones are marked, never corrected); no-CAS rows are labelled. */
      const casList = window.CasDissect ? CasDissect.casOf(x) : '';
      let casHtml;
      if (casList) {
        casHtml = casList.split(',').map(c =>
          CasDissect.casChecksum(c) === false
            ? '<span class="cas-bad" title="' + t('cas.badsum', 'رقم التحقق غير صحيح في بيانات المصدر') + '">' + esc(c) + '</span>'
            : esc(c)).join(' · ');
      } else if (x.r.cas) {
        casHtml = esc(String(x.r.cas).replace(/\n/g, ' · '))
          + ' <span class="nocas">(' + t('cas.nocas', 'بلا رقم في المصدر') + ')</span>';
      } else {
        casHtml = t('cas.missing', 'غير متوفر');
      }
      const strong = x.s.v >= 90;
      const raw = x.r.status_raw && showDetails
        ? '<p class="match">' + t('results.source.raw', 'الحالة كما وردت في المصدر:') + ' ' + esc(x.r.status_raw) + '</p>'
        : '';
      const cat = x.r.category && showDetails
        ? '<p class="match">' + t('results.source.category', 'التصنيف كما ورد في المصدر:') + ' ' + esc(x.r.category) + '</p>'
        : '';
      const matchType = showDetails
        ? '<p class="match">' + esc(x.s.type) + ': ' + esc(x.s.field) + '</p>'
        : '';
      const badge = '<span class="badge ' + (strong
        ? 'strong">' + t('results.badge.strong', 'تطابق قوي')
        : 'possible">' + t('results.badge.possible', 'تطابق محتمل')) + '</span>';
      const bar = '<div class="scorebar" aria-hidden="true"><i style="width:'
        + Math.min(100, x.s.v) + '%"></i></div>';
      return '<article class="result ' + (strong ? '' : 'possible') + '">'
        + '<div class="result-top"><div><span class="source">' + esc(sourceLabel(x.k)) + '</span>'
        + '<h3>' + esc(x.r.name || t('results.noname', 'بدون اسم')).replace(/\n/g, ' · ') + '</h3>'
        + badge + verdict + '</div>'
        + '<strong>' + x.s.v + '%</strong></div>'
        + bar
        + '<p class="status ' + stClass + '">' + esc(sd.text) + '</p>'
        + '<p class="meta">' + t('cas.label', 'CAS:') + ' ' + casHtml + '</p>'
        + cat + raw + matchType
        + (!strong ? '<p class="caution">' + t('results.caution', 'تطابق محتمل، راجع الاسم والملصق قبل الاستخدام.') + '</p>' : '')
        + '</article>';
    }).join('');
  }

  /* ============================================================
   * Search history (IndexedDB "history" store, capped at 50)
   * ============================================================ */
  function addHistory(q, hits) {
    if (!q) return;
    const rand = Math.random().toString(36).slice(2, 7);
    const entry = { q, hits, at: Date.now(), rand };
    // One atomic transaction: add the entry and trim to the newest 50.
    // Keys 'h:<13-digit-ms>:<rand>' sort chronologically.
    openDB().then(db => new Promise((resolve, reject) => {
      const tx = db.transaction(STORE_HISTORY, 'readwrite');
      const store = tx.objectStore(STORE_HISTORY);
      store.put(entry, 'h:' + entry.at + ':' + rand);
      const gk = store.getAllKeys();
      gk.onsuccess = () => {
        const keys = (gk.result || []).sort();
        for (let i = 0; i < Math.max(0, keys.length - 50); i++) store.delete(keys[i]);
      };
      tx.oncomplete = resolve;
      tx.onerror = () => reject(tx.error);
      tx.onabort = () => reject(tx.error);
    })).catch(() => {});
  }

  function renderHistory(items) {
    const box = $('#historyList');
    if (!items.length) {
      box.innerHTML = '<div class="notice">' + t('history.empty', 'لا يوجد سجل بحث بعد.') + '</div>';
      return;
    }
    box.innerHTML = items
      .sort((a, b) => (b.at || 0) - (a.at || 0))
      .map(x => '<div class="history-item" data-q="' + esc(x.q) + '">'
        + '<span>' + esc(x.q) + '</span><span class="history-meta">'
        + (x.hits || 0) + ' · '
        + new Date(x.at || Date.now()).toLocaleString(I18N.getLang ? I18N.getLang() : 'ar') + '</span></div>')
      .join('');
  }

  function openHistory() {
    idbGetAll(STORE_HISTORY).then(renderHistory).catch(() => {
      $('#historyList').innerHTML = '<div class="notice">' + t('history.fail', 'تعذّر قراءة السجل.') + '</div>';
    });
  }

  /*
   * Wiring
   * ============================================================ */
  const DB = {};   // key -> validated data object (or absent if unavailable)
  let searchFn = null;
  let lastResults = [];   // most recent rendered results (for live mode re-render)

  /*
   * The search index is rebuilt ONLY when the set of loaded databases
   * actually changes (phase/count of any source). Rows are immutable
   * while loaded, so caching the index between searches is safe and
   * produces identical results — it just avoids re-normalizing ~8,000
   * fields on every submit (measured ~26 ms per search on desktop;
   * several times that on low-end phones, all on the main thread).
   */
  let cachedIndexSig = null;
  let cachedSearch = null;

  function rebuildSearch() {
    const sig = SOURCES.map(s => s.key + ':' + state[s.key].phase + ':' + state[s.key].count).join('|');
    if (cachedSearch && sig === cachedIndexSig) { searchFn = cachedSearch; return; }
    const sources = SOURCES.map(s => ({ key: s.key, rows: (DB[s.key] || {}).rows || null }));
    searchFn = SearchCore.buildSearch(sources);
    cachedSearch = searchFn;
    cachedIndexSig = sig;
  }

  $('#searchForm').addEventListener('submit', e => {
    e.preventDefault();
    const q = $('#query').value.trim();
    if (!q) return;
    rebuildSearch();                       // include newly arrived databases
    if (!searchFn || !searchFn.sources.length) {
      $('#results').innerHTML = '<div class="notice warn"><b>' + t('search.noDB.t', 'قواعد البيانات غير متاحة') + '</b><br>'
        + t('search.noDB.b', 'تعذّر تحميل قاعدة واحدة على الأقل، لذلك لا يمكن تنفيذ البحث.') + '</div>';
      $('#resultTitle').textContent = t('results.title2', 'نتائج الفحص');
      return;
    }
    const pro = $('#mode').value === 'pro';
    const results = searchFn(q, pro);
    render(results, q);
    if (results.length) addHistory(q, results.length);
  });

  $('#mode').addEventListener('change', () => {
    $('#modeLabel').textContent = $('#mode').value === 'pro'
      ? t('mode.pro', 'المحترف') : t('mode.farmer', 'المزارع');
    /* Re-render the current results so the detail level switches live
     * (farmer = simplified verdict, professional = full evidence). */
    const first = $('#results .result') || $('#results .prohibited');
    if (first && lastResults.length) render(lastResults, $('#query').value.trim());
  });

  window.addEventListener('online', renderDbStatus);
  window.addEventListener('offline', renderDbStatus);

  /* Live language switch: re-render every dynamic string in place.
   * Static text is handled by I18N.apply(); DB status values stay
   * verbatim (source-of-truth strings are never translated). */
  document.addEventListener('langchange', () => {
    renderDbStatus();
    updateOnlineBadge();
    if (lastResults.length) render(lastResults, $('#query').value.trim());
    updatePrepPanel();
  });

  /* History panel */
  $('#historyBtn').addEventListener('click', () => {
    const p = $('#historyPanel');
    p.hidden = !p.hidden;
    if (!p.hidden) openHistory();
  });
  $('#historyClose').addEventListener('click', () => { $('#historyPanel').hidden = true; });
  $('#historyClear').addEventListener('click', () => {
    idbClear(STORE_HISTORY).then(openHistory).catch(() => {});
  });
  $('#historyList').addEventListener('click', e => {
    const item = e.target.closest('.history-item');
    if (!item) return;
    $('#query').value = item.dataset.q || '';
    $('#searchForm').dispatchEvent(new Event('submit', { cancelable: true }));
  });

  /* Copy report */
  $('#copyBtn').addEventListener('click', () => {
    navigator.clipboard && navigator.clipboard.writeText($('#results').innerText).catch(() => {});
  });

  /* Camera / gallery -> offline OCR (src/ocr.js) -> EXISTING search engine.
     The 80% threshold and source priority live in SearchCore and are not
     touched here; this only feeds candidate text into the same search(). */
  const camera = $('#camera'), preview = $('#preview'), ocrMsg = $('#ocrMsg');
  let ocrBusy = false;
  let previewUrl = null;   // revoke old blob URLs so repeated scans don't leak memory

  function showPreview(file) {
    if (previewUrl) { try { URL.revokeObjectURL(previewUrl); } catch (e) {} }
    previewUrl = URL.createObjectURL(file);
    preview.src = previewUrl;
    preview.hidden = false;
    $('#scanPanel').open = true;
  }

  $('#cameraBtn').addEventListener('click', () => camera.click());
  camera.addEventListener('change', () => {
    const f = camera.files && camera.files[0];
    if (!f) return;
    showPreview(f);
    runOcr(f);
  });

  /* Gallery selection — same OCR pipeline, no second workflow */
  const gallery = $('#gallery');
  $('#galleryBtn').addEventListener('click', () => gallery.click());
  gallery.addEventListener('change', () => {
    const f = gallery.files && gallery.files[0];
    if (!f) return;
    showPreview(f);
    runOcr(f);
  });

  /* Run candidate text through the existing search and merge results. */
  function searchCandidates(casList, candList) {
    rebuildSearch();
    if (!searchFn || !searchFn.sources.length) return [];
    const rank = { 'libya-248': 0, 'libya-500': 1, eu: 2, epa: 3, fao: 4 };
    /* Keep the BEST score per row: a weak fuzzy hit from a candidate like
     * "Bifenthrin 7.9" must never mask the exact 100% match for the same
     * row that another candidate ("Bifenthrin") already produced. */
    const byRow = new Map();
    const pushAll = list => (list || []).forEach(x => {
      const prev = byRow.get(x.r);
      if (!prev || x.s.v > prev.s.v) byRow.set(x.r, x);
    });
    for (const cas of casList) pushAll(searchFn(cas, true));   // CAS exact (100%)
    for (const cand of candList) pushAll(searchFn(cand, false)); // same 80% rule
    const merged = [...byRow.values()];
    merged.sort((a, b) => ((rank[a.k] ?? 99) - (rank[b.k] ?? 99)) || (b.s.v - a.s.v));
    return merged.slice(0, 24);
  }

  function showOcrResults(merged, noneMsg) {
    $('#resultTitle').textContent = t('ocr.title', 'نتائج المسح البصري');
    if (merged.length) {
      render(merged, '');
    } else {
      $('#results').innerHTML = '<div class="notice warn"><b>' + noneMsg
        + '</b><br>' + t('ocr.none.b', 'عدّل النص المكتشف أو اكتب الاسم/CAS يدويًا في حقل البحث.') + '</div>';
    }
  }

  /* د4 — image quality probe BEFORE reading: sharpness (Laplacian-ish
   * gradient energy), glare (blown-out highlights ratio) and light level.
   * Returns a guidance key list; advisory only, never blocks the scan. */
  function probeImage(file) {
    return new Promise(resolve => {
      const img = new Image();
      const url = URL.createObjectURL(file);
      img.onload = () => {
        try {
          const w = Math.min(320, img.width || 320), h = Math.max(1, Math.round((img.height || 240) * w / (img.width || 320)));
          const c = document.createElement('canvas'); c.width = w; c.height = h;
          const g = c.getContext('2d', { willReadFrequently: true });
          g.drawImage(img, 0, 0, w, h);
          const d = g.getImageData(0, 0, w, h).data;
          let lap = 0, blown = 0, dark = 0, n = 0;
          for (let y = 1; y < h - 1; y++) for (let x = 1; x < w - 1; x++) {
            const i = (y * w + x) * 4;
            const g2 = (d[i] * 299 + d[i + 1] * 587 + d[i + 2] * 114) / 1000 | 0;
            const gx = d[i + 4] - d[i - 4];
            const gy = d[i + w * 4] - d[i - w * 4];
            lap += Math.abs(gx) + Math.abs(gy);
            if (g2 > 250) blown++;
            if (g2 < 25) dark++;
            n++;
          }
          URL.revokeObjectURL(url);
          const keys = [];
          if (n && lap / n < 6) keys.push('ocr.tip.blur');
          if (n && blown / n > 0.08) keys.push('ocr.tip.glare');
          if (n && dark / n > 0.45) keys.push('ocr.tip.dark');
          resolve(keys);
        } catch (e) { URL.revokeObjectURL(url); resolve([]); }
      };
      img.onerror = () => { URL.revokeObjectURL(url); resolve([]); };
      img.src = url;
    });
  }

  /* د5 — local diagnostics log (localStorage, capped, no images, no upload).
   * Export is manual-only via the button; nothing is ever sent anywhere. */
  const DIAG_KEY = 'mustashar-diag';
  function diagAdd(entry) {
    try {
      const list = JSON.parse(localStorage.getItem(DIAG_KEY) || '[]');
      list.push(entry);
      while (list.length > 100) list.shift();
      localStorage.setItem(DIAG_KEY, JSON.stringify(list));
    } catch (e) { /* storage may be unavailable */ }
  }
  function diagExport() {
    try {
      const list = JSON.parse(localStorage.getItem(DIAG_KEY) || '[]');
      const blob = new Blob([JSON.stringify(list, null, 1)], { type: 'application/json' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = 'mustashar-diagnostics-' + new Date().toISOString().slice(0, 10) + '.json';
      a.click();
      setTimeout(() => URL.revokeObjectURL(a.href), 2000);
    } catch (e) {}
  }

  /* د4 — confirmation step: after OCR, the user confirms/edits the extracted
   * active-ingredient candidates BEFORE any search is run or saved. */
  let pendingScan = null;   // { res, tips }
  function showConfirmPanel(res, tips) {
    const sel = $('#aiConfirm');
    if (!sel) { proceedWithScan(res); return; }
    pendingScan = { res, tips };
    sel.innerHTML = '';
    const opts = (res.candidates || []).filter(c => /^[A-Za-z\u0600-\u06FF]/.test(c)).slice(0, 8);
    if (!opts.length) { proceedWithScan(res); return; }
    opts.forEach((c, i) => {
      const o = document.createElement('option');
      o.value = c; o.textContent = c;
      sel.appendChild(o);
    });
    $('#confirmPanel').hidden = false;
    $('#ocrActions').hidden = false;
    $('#ocrText').value = res.text || '';
    ocrMsg.textContent = tips.length
      ? t('ocr.tips', 'ملاحظات على الصورة:') + ' ' + tips.map(k => t(k, k)).join(' · ')
      : t('ocr.confirm', 'راجع المادة الفعالة المقروءة ثم اضغط «بحث».');
  }
  function proceedWithScan(res) {
    showOcrResults(
      searchCandidates(res.cas, res.candidates),
      t('ocr.none.t', 'لم يتم العثور على تطابق موثوق من النص المكتشف'));
  }
  $('#aiConfirmBtn').addEventListener('click', () => {
    if (!pendingScan) return;
    const chosen = $('#aiConfirm').value;
    const res = pendingScan.res;
    pendingScan = null;
    $('#confirmPanel').hidden = true;
    const cands = chosen ? [chosen, ...res.candidates.filter(c => c !== chosen)] : res.candidates;
    diagAdd({ at: Date.now(), confirmed: chosen, passes: res.passes, conf: res.confidence,
      variant: res.variant, psm: res.psm, top: (res.best || {}).name || '', cas: res.cas.join(',') });
    showOcrResults(searchCandidates(res.cas, cands),
      t('ocr.none.t', 'لم يتم العثور على تطابق موثوق من النص المكتشف'));
  });
  $('#aiConfirmSkip').addEventListener('click', () => {
    if (!pendingScan) return;
    const res = pendingScan.res; pendingScan = null;
    $('#confirmPanel').hidden = true;
    diagAdd({ at: Date.now(), confirmed: '(skipped)', passes: res.passes, conf: res.confidence });
    proceedWithScan(res);
  });
  $('#diagBtn').addEventListener('click', diagExport);

  async function runOcr(file) {
    if (ocrBusy || typeof OcrModule === 'undefined') return;
    ocrBusy = true;
    $('#cancelOcrBtn').hidden = false;
    ocrMsg.textContent = t('ocr.prep', 'جارٍ تجهيز الصورة…');
    const t0 = performance.now();
    const tips = await probeImage(file);
    try {
      rebuildSearch();   // ensure the 4-DB index is current before DB-aware OCR scoring
      const msgs = {};
      for (const k of ['ocr.prep','ocr.init','ocr.loading','ocr.pass','ocr.roi','ocr.rotate','ocr.done']) msgs[k] = t(k, k);
      const res = await OcrModule.recognize(file, p => {
        if (!p) return;
        if (p.statusKey) ocrMsg.textContent = (p.status || p.statusKey) + (p.progress ? ' (' + Math.round(p.progress * 100) + '%)' : '');
        else if (p.status === 'done') ocrMsg.textContent = t('ocr.done', 'اكتملت القراءة.');
        else {
          const pct = Math.round((p.progress || 0) * 100);
          ocrMsg.textContent = p.status + (pct ? ' (' + pct + '%)' : '');
        }
      }, { search: searchFn, messages: msgs });   // DB-aware pass scoring + i18n keys
      const ms = Math.round(performance.now() - t0);
      const textLen = (res.text || '').replace(/\s/g, '').length;
      const weak = textLen < 6 || (res.confidence !== null && res.confidence < 40);
      if (weak) {
        /* د4 safe failure: no guessing — ask for manual entry */
        ocrMsg.textContent = t('ocr.weak.manual', 'لم أستطع القراءة بثقة كافية — أدخل الاسم يدويًا في حقل البحث، أو عدّل النص أدناه.');
        $('#ocrText').value = res.text || '';
        $('#ocrActions').hidden = false;
        $('#cancelOcrBtn').hidden = true;
        diagAdd({ at: Date.now(), outcome: 'weak', ms, passes: res.passes });
        return;
      }
      diagAdd({ at: Date.now(), outcome: 'scanned', ms, passes: res.passes, conf: res.confidence, variant: res.variant });
      showConfirmPanel(res, tips);   // confirmation step before any search
    } catch (e) {
      const cancelled = e && String(e.message || e).indexOf('ocr.cancelled') === 0;
      ocrMsg.textContent = cancelled
        ? t('ocr.cancelled', 'أُلغي المسح.')
        : t('ocr.fail', 'تعذّر تشغيل محرك القراءة.');
      diagAdd({ at: Date.now(), outcome: cancelled ? 'cancelled' : 'error', ms: Math.round(performance.now() - t0) });
    } finally {
      ocrBusy = false;
      $('#cancelOcrBtn').hidden = true;
    }
  }
  $('#cancelOcrBtn').addEventListener('click', () => {
    if (typeof OcrModule !== 'undefined') OcrModule.cancelCurrent();
  });

  /* Re-search from (possibly edited) OCR text — same pipeline, same rules. */
  $('#ocrRerun').addEventListener('click', () => {
    if (typeof OcrModule === 'undefined') return;
    const text = $('#ocrText').value || '';
    const cas = OcrModule.extractCAS(text);
    const cands = OcrModule.extractCandidates(text);
    showOcrResults(searchCandidates(cas, cands),
      t('ocr.none.t2', 'لم يتم العثور على تطابق موثوق من النص المدخل'));
  });

  /* ============================================================
   * Offline preparation panel — «تجهيز العمل بدون إنترنت»
   * Shows what is already stored (with real byte sizes read from
   * Cache Storage), whether search and OCR are ready offline, and a
   * single explicit prepare action. No hidden or repeated downloads:
   * assets are fetched once (or already cached by a first online scan)
   * and afterwards served exclusively from cache.
   * ============================================================ */
  const SHELL_PATHS = ['index.html', 'src/search-core.js', 'src/app.js', 'src/ocr.js',
    'manifest.json', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-512.png'];
  const DATA_PATHS = ['data/libya-248.json', 'data/libya-500.json', 'data/eu.json', 'data/epa.json'];
  const OCR_ASSET_PATHS = [
    'vendor/tesseract/tesseract.min.js',
    'vendor/tesseract/worker.min.js',
    'vendor/tesseract/core/tesseract-core-simd-lstm.wasm.js',
    'vendor/tesseract/core/tesseract-core-simd-lstm.wasm',
    'vendor/tesseract/core/tesseract-core-lstm.wasm.js',
    'vendor/tesseract/core/tesseract-core-lstm.wasm',
    'vendor/tesseract/lang/eng.traineddata.gz',
    'vendor/tesseract/lang/ara.traineddata.gz'
  ];

  /* Find a cached response for a path in ANY app cache (current, OCR,
   * or a previous version) and measure its real size. Opening only
   * cache names that already exist — never creates caches. */
  async function measureCached(paths) {
    try {
      const names = await caches.keys();
      let bytes = 0, ready = 0;
      for (const p of paths) {
        const url = new URL(p, location.href);
        let hit = null;
        for (const name of names) {
          const c = await caches.open(name);
          hit = await c.match(url.href);
          if (hit) break;
        }
        if (!hit) return { ready: false, bytes: 0 };
        ready++;
        const len = parseInt(hit.headers.get('content-length') || '', 10);
        bytes += (Number.isFinite(len) && len > 0)
          ? len
          : (await hit.clone().arrayBuffer()).byteLength;
      }
      return { ready: ready === paths.length, bytes };
    } catch (e) { return { ready: false, bytes: 0 }; }
  }

  const fmtMB = b => (b / 1048576).toFixed(1) + ' ' + t('prep.mb', 'ميجابايت');

  function setPrepItem(liId, sizeId, info) {
    const li = $(liId), sz = $(sizeId);
    if (!li) return;
    li.classList.toggle('done', !!info.ready);
    if (sz) sz.textContent = info.ready ? fmtMB(info.bytes) : '—';
  }

  let prepMeasured = false;
  async function updatePrepPanel() {
    const st = $('#prepState'), btn = $('#prepBtn');
    if (!st) return;
    if (!window.caches) { st.textContent = t('prep.noStorage', 'المتصفح لا يدعم التخزين المحلي الكامل'); return; }
    const [shell, data, ocr] = await Promise.all([
      measureCached(SHELL_PATHS), measureCached(DATA_PATHS), measureCached(OCR_ASSET_PATHS)
    ]);
    prepMeasured = true;
    setPrepItem('#prepShell', '#prepShellSize', shell);
    setPrepItem('#prepData', '#prepDataSize', data);
    setPrepItem('#prepOcr', '#prepOcrSize', ocr);
    if (shell.ready && data.ready && ocr.ready) {
      st.textContent = t('prep.full', 'جاهز للعمل بدون إنترنت ✅');
      st.className = 'chip active';
      if (btn) { btn.textContent = t('prep.done', '✅ التطبيق مجهز بالكامل'); btn.disabled = true; }
    } else if (shell.ready && data.ready) {
      st.textContent = t('prep.searchReady', 'البحث جاهز دون إنترنت — المسح البصري بحاجة للتجهيز');
      if (btn) { btn.textContent = t('prep.ocrBtn', '⬇️ تجهيز ملفات المسح البصري'); btn.disabled = false; }
    } else {
      st.textContent = t('prep.firstRun', 'أكمل أول تشغيل أثناء الاتصال ليكتمل التجهيز');
      if (btn) { btn.textContent = t('prep.btn', '⬇️ تجهيز الآن'); btn.disabled = false; }
    }
  }

  /* One explicit preparation action (OCR assets + missing shell/data).
     Persistence is re-requested here: a user gesture is the strongest
     signal an engine can get, so asking at the exact moment the user
     opts into ~19 MB of local data maximizes the chance the stored
     databases/OCR are protected from eviction. */
  $('#prepBtn').addEventListener('click', async () => {
    if (typeof OcrModule === 'undefined') return;
    const btn = $('#prepBtn'), st = $('#prepState');
    btn.disabled = true;
    st.textContent = t('prep.working', 'جارٍ التجهيز…');
    requestPersistence();
    ocrMsg.textContent = t('ocr.loading', 'جارٍ تحميل ملفات المسح البصري للاستخدام دون إنترنت…');
    try {
      const n = await OcrModule.prefetch();
      prepMeasured = false;                 // re-measure with fresh data
      await updatePrepPanel();
      ocrMsg.textContent = tf('ocr.loadDone', 'تم تحميل ملفات OCR ({n}/8). سيعمل المسح البصري دون إنترنت.', { n: n });
    } catch (e) {
      st.textContent = t('prep.fail', 'تعذّر التجهيز الآن — أعد المحاولة أثناء الاتصال');
      ocrMsg.textContent = t('prep.failNote', 'تعذّر تحميل ملفات OCR الآن. سيُعاد المحاولة تلقائيًا عند أول مسح أثناء الاتصال.');
    }
    btn.disabled = false;
  });

  /* Support/contact button: reads config/support.json; hidden when empty.
   * No payment integration by design (user decision 5). */
  (function initSupport() {
    const btn = $('#supportBtn');
    if (!btn) return;
    fetch('config/support.json', { cache: 'no-store' }).then(r => (r.ok ? r.json() : null)).then(cfg => {
      if (!cfg || (!cfg.contact && !cfg.url)) return;   // stays hidden
      btn.hidden = false;
      btn.textContent = cfg.label || t('support.label', 'ادعم أو تواصل');
      btn.addEventListener('click', () => {
        if (cfg.url) window.open(cfg.url, '_blank', 'noopener');
        else if (cfg.contact) location.href = cfg.contact;
      });
    }).catch(() => { /* hidden = safe default */ });
  })();

  /* Theme (now persisted) */
  const themeBtn = $('#themeToggle');
  try {
    const saved = localStorage.getItem('mustashar-theme');
    if (saved) document.documentElement.dataset.theme = saved;
  } catch (e) { /* storage may be unavailable */ }
  themeBtn.addEventListener('click', () => {
    const next = document.documentElement.dataset.theme === 'dark' ? '' : 'dark';
    if (next) document.documentElement.dataset.theme = next;
    else delete document.documentElement.dataset.theme;
    try { localStorage.setItem('mustashar-theme', next || 'light'); } catch (e) {}
  });

  /* Service worker registration + update detection */
  function updateOnlineBadge() {
    $('#offlineState').textContent = navigator.onLine
      ? t('chip.online', '🟢 متصل') : t('chip.offline', '🔴 بدون إنترنت');
  }
  window.addEventListener('online', updateOnlineBadge);
  window.addEventListener('offline', updateOnlineBadge);
  updateOnlineBadge();

  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('./sw.js').then(reg => {
      reg.addEventListener('updatefound', () => {
        const nw = reg.installing;
        if (!nw) return;
        nw.addEventListener('statechange', () => {
          if (nw.state === 'installed' && navigator.serviceWorker.controller) {
            const banner = $('#dbBanner');
            if (banner) {
              banner.hidden = false;
              banner.className = 'banner banner-info';
              banner.textContent = t('sw.update', 'يتوفر تحديث للتطبيق. أعد تحميل الصفحة للتحديث — لن يتم حذف أي بيانات محفوظة.');
            }
          }
        });
      });
      return navigator.serviceWorker.ready;
    }).then(() => updatePrepPanel()).catch(() => {});
  }

  /* ============================================================
   * Boot
   * ============================================================ */
  renderDbStatus();
  requestPersistence();
  loadAll();
  checkVersion();
  updatePrepPanel();          // works even if the SW is still installing
})();
